---
- hosts: all
  connection: winrm
  vars:
    reboot_after_updates: no  
  tasks:
    - name: Check for available updates 
      win_updates:
        state: searched
      register: available_updates

    - name: Print available updates
      debug:
        var: available_updates.stdout_lines
