- name: Run Updates on App Servers and wait 10 mins
  hosts: all
  connection: winrm

  tasks:
    ansible.windows.win_updates:
      category_names:
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
    reboot: yes
    reboot_timeout: 600