---
- name: Patch Windows Servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure the win_updates module is available
      ansible.windows.win_feature:
        name: PowerShell
        state: present

    - name: Check for available updates
      ansible.windows.win_updates:
        category_names: ['CriticalUpdates', 'SecurityUpdates','UpdateRollups','FeaturePacks']
      register: update_result

    - name: Display update summary
      debug:
        msg: "Updates installed: {{ update_result.updates }}"

