---
- name: Check for Windows Updates on Windows
  hosts: all
  become: true
  gather_facts: no
  become_user: "amsible"

  tasks:
    - name: Check for Windows updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - FeaturePacks
        state: searched
      register: update_info

    - name: Display available updates
      debug:
        msg: "{{ update_info.updates }}"

