---
- name: Check for Windows Updates on Windows 11
  hosts: windows
  become: yes
  gather_facts: no

  tasks:
    - name: Check for Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - FeaturePacks
        state: searched
      register: update_info

    - name: Display available updates
      debug:
        msg: "{{ update_info.updates }}"
