---
- hosts: all
  become: true
  connection: winrm
  vars:
    reboot_after_updates: no  

  tasks:
    - name: Check for available updates (optional)
      win_updates:
        state: search
      register: available_updates

