---
- name: Patch Windows Servers
  hosts: all
  gather_facts: no
  tasks:
    - name: Install Windows updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
        register: available_updates


    - name: Display installed security updates
      debug:
        msg: "{{ available_updates }}"
