---
- name: Patch Windows Servers
  hosts: windows
  gather_facts: no
  tasks:
    - name: Install Windows updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - DefinitionUpdates
          - SecurityUpdates
          - Updates
        reboot: no
        reboot_timeout: 600
