---
- name: Check for Windows Updates on Windows
  hosts: all
  become: true
  gather_facts: no
  become_user: amsible
  become_password: ansible
  tasks:
    - name: Check for Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - FeaturePacks
        state: searched
      register: update_info

    - name: Display available updates
      debug:
        msg: "{{ update_info.updates }}"


  vars:
    machine:
      win_admin_user: '{{ ansible_user }}'
      win_admin_password: '{{ ansible_password }}'