---
- hosts: all
  gather_facts: no
  become: true
  become_method: runas
  become_user: {{ admin_user }}

  vars:
    reboot_after_updates: no  
  tasks:
    - name: Check for available updates
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        state: searched
      register: available_updates

    - name: Print available updates
      debug:
        var: available_updates
