---
- name: Provision EC2 Instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch an EC2 Instance
      amazon.aws.ec2_instance:
        name: "Test-Ansible-Aws-EC2"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group }}"
        count: "{{ count }}"
        wait: yes
        aws_region: "{{ region }}"
        network:
          assign_public_ip: true
        image_id: "{{ ami }}"
        register: ec2_instance

    - name: Display Output
      ansible.builtin.debug:
        msg: "{{ ec2_instance.stdout_lines }}"

