---
- name: Provision EC2 Instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        wait: yes
        wait_timeout: 500
        count: "{{ count }}"
      register: ec2_instance

    - name: Display Output
      ansible.builtin.debug:
        msg: "{{ ec2_instance.stdout_lines }}"

