---
- name: Print-Message
  hosts: all
  gather_facts: no

  tasks:
    - name: Print-Message
      ansible.builtin.shell: echo "Welcome :{{ message }}"
      register: print_message

    - name: Display message
      ansible.builtin.debug:
        msg: "{{ print_message.stdout_lines }}"
