- name: Manage Updates and Patching on Windows
  hosts: all 
#  become: true
  become_method: runas
  collections:
    - ansible.windows

  tasks:
    - name: Check for available Windows updates
      win_updates:
        state: present
        category_name: "*"
      register: updates

    - name: Display available updates (optional)
      debug:
        msg: "{{ updates.result }}"

#    - name: Install available Windows updates
#      win_updates:
#        state: present
#        category_name: "{{ update_category }}"
#        reboot: yes
#      when: updates.result.available != 0

  vars:
    update_category: "*"  # Update all categories by default