---
- name: Manage files and services on Windows
  hosts: all 

  tasks:
    - name: Create a directory
      ansible.windows.win_file:
        path: C:\demo-ansible\windows-example
        state: directory
