---
- name: Creating an EC2 Instance with Creating a VPC and Subnet Id
  hosts: localhost
  tasks:
    - name: Launch an EC2 Instance
      amazon.aws.ec2_instance:
        name: "Test-Ansible-Create-EC2"
        access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID') }}"
        secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_ACCESS_KEY') }}"
        instance_type: "{{ instance_type }}"
        count: "{{ count }}"
        wait: yes
        aws_region: "{{ region }}"
        network:
          assign_public_ip: true
        image_id: "{{ ami }}"
      register: aws_ec2    

    - ansible.builtin.debug:
        var: aws_ec2

