---
- name: Check for Security Patches in RHEL 9
  hosts: all
  become: true

  tasks:
    - name: Ensure dnf-plugins-core is installed
      yum:
        name: dnf-plugins-core
        state: present

    - name: List available security updates
      shell: dnf updateinfo list security
      register: security_updates

    - name: Display security updates
      debug:
        var: security_updates
