---
- name: Check for and Install "{{ sec_level }}" Security Patches in RHEL / Fedora
  hosts: all
  become: true
  ignore_unreachable: yes

  tasks:
    - name: Ensure dnf-plugins-core is installed
      yum:
        name: dnf-plugins-core
        state: present

    - name: List available security updates
      shell: dnf updateinfo list security
      register: security_updates

    - name: Display all available security updates
      debug:
        msg: "{{ security_updates.stdout.split('\n') }}"

    # Critical,Important,Moderate,Low
    - name: Filter and install security updates
      shell: |
        updates=$(dnf updateinfo list security | grep -i "{{ sec_level }}" | awk '{print $3}')
        if [ ! -z "$updates" ]; then
          dnf update -y $updates
        fi
      register: update_result
      changed_when: update_result.rc == 0

    - name: Display applied moderate security updates
      debug:
        msg: "{{ update_result.stdout.split('\n') }}"
