---
- name: Check for Security Patches in RHEL
  hosts: all
  become: true

  tasks:
    - name: Install yum-plugin-security
      yum:
        name: yum-plugin-security
        state: present

    - name: List available security updates
      shell: yum updateinfo list security all
      register: security_updates

    - name: Display security updates
      debug:
        var: security_updates.stdout
