---
- name: Install httpd in rhel
  hosts: all
  tasks:
    - name: Install httpd
      ansible.builtin.package:
        name: httpd
        state: present
    - name: Start and enable httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

