---
- name: Create test directory /root location
  hosts: all
  gather_facts: no

  tasks:
    - name: Create test directory /root location
      ansible.builtin.shell: mkdir -p  /root/demo-test-19-dec-2024
      register: create_dir

    - name: Display directory creation
      ansible.builtin.debug:
        msg: "{{ create_dir.stdout_lines }}"

    - name: List  /root location
      ansible.builtin.shell: ls -l  /root
      register: list_root

    - name: Display files
      ansible.builtin.debug:
        msg: "{{ list_root.stdout_lines }}"
