---
- name: Example playbook with vars_prompt
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Print the username
      debug:
        msg: "The entered username is {{ username }}"

    - name: Print the age
      debug:
        msg: "The entered age is {{ age }}"

    - name: Print a masked password (not recommended for actual use)
      debug:
        msg: "The entered password is {{ password }} (this should be kept secret)"
