---
- name: Uninstall Apache HTTPD
  hosts: all
  tasks:

    - name: Stop httpd service if running
      ansible.builtin.service:
        name: httpd
        state: stopped
        enabled: no
      ignore_errors: yes  # Just in case it's not running

    - name: Uninstall httpd package
      ansible.builtin.package:
        name: httpd
        state: absent

    - name: Remove leftover configuration (optional)
      ansible.builtin.file:
        path: /etc/httpd
        state: absent
      ignore_errors: yes
