---
- name: Uninstall Apache HTTPD
  hosts: all
  tasks:

    - name: Stop httpd service if running
      shell: |                
          systemctl stop httpd 

    - name: Uninstall httpd package
      shell: |                
          dnf remove httpd -y

    - name: Remove leftover configuration (optional)
      shell: |                
          systemctl daemon-reload
          